version: '3.9'
services:
  wetty:
    build:
      context: ./wetty
    entrypoint: yarn start --ssh-host kali --ssh-user ${USER_NAME} --ssh-pass ${USER_PASSWORD}  --base / --allow-iframe true
    ports:
      - ${WETTY_PORT}:3000

  kali:
    build:
      context: ./kali
    tty: true
    # ユーザーを作成してssh server起動
    command: >
      bash -c "
      useradd -m ${USER_NAME} &&
      echo '${USER_NAME}:${USER_PASSWORD}' | chpasswd &&
      usermod -aG sudo ${USER_NAME} &&
      chsh -s /bin/bash ${USER_NAME} &&
      service ssh start &&
      /bin/bash
      "
